### ISSUE TITLE
Typo in tutorial 4; "Buffers and Indices"

### ISSUE THREAD

**Issue by Busata** [sotrh/learn-wgpu#106]
"To import the extension trait, this line somewhere near the top of main.rs":

use wgpu::DeviceExt;

should probably be use wgpu::util::DeviceExt;

thanks!

**Comment by Busata** [comment]
(It seems up to date in the code, but not on https://sotrh.github.io/learn-wgpu/beginner/tutorial4-buffer/#the-vertex-buffer) ?

**Comment by sotrh** [comment]
I forgot to run `deploy.sh`. It should be up to date now :)
