### ISSUE TITLE
renderpass setup 

### ISSUE THREAD

**Issue by benmkw** [sotrh/learn-wgpu#111]
> The order of these statements is important. The pipeline needs to be set first, then the bind groups, vertex buffers, and index buffer, finally the draw call. If you don't do this, you'll likely get a crash.

I asked about that on matrix and was told:

> that's not actually true, you can bind them in any order as long as they're all bound by the time you draw
> the one exception is push constants which have to be bound after the pipeline, but that's a bug

**Comment by sotrh** [comment]
At time of writing, it was an issue. They've since fixed it so that you don't have to bind things in any particular order. I should remove that statement.

**Comment by benmkw** [comment]
Just to clarify I did not mean this in a bad way, just remembered that I asked and wanted to let you know 👍

**Comment by sotrh** [comment]
I didn't feel offended :) I tend to be terse sometimes.

**Comment by benmkw** [comment]
ok 👍
