### ISSUE TITLE
Incorrect use of `cargo:rerun-if-changed`

### ISSUE THREAD

**Issue by chinedufn** [sotrh/learn-wgpu#119]
Hey!

Just a heads up that the `rerun-if-changed` across many of the examples will not work.

```rust
use std::path::PathBuf;

fn main () {
    let path = PathBuf::from("src/foo.vert.glsl");
    
    // Incorrect
    println!("cargo:rerun-if-changed={:?}", path);
    
    // Correct
    println!("cargo:rerun-if-changed={}", path.to_str().unwrap());

    // Also correct
    println!("cargo:rerun-if-changed={}", path.display());
}
```

Output:

```
cargo:rerun-if-changed="src/foo.vert.glsl"
cargo:rerun-if-changed=src/foo.vert.glsl
cargo:rerun-if-changed=src/foo.vert.glsl
```

Note that the debug representation includes quotation marks, which cargo does not respect.

**Comment by chinedufn** [comment]
Related

#108 
6f29ba738be4ea6e6e1eb57a10dd210d03a6c031

**Comment by kanerogers** [comment]
@sotrh Can this issue now be closed?

**Comment by sotrh** [comment]
I haven't merge #122 into master yet. I was going to wait until I finished the imgui demo, but I might just merge it.

**Comment by kanerogers** [comment]
Sounds good to me. 👌
