### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dhardy** [sotrh/learn-wgpu#12]
I have a few comments while reading, so I'll just put them here.

This paragraph is now outdated: https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#what-s-with-the-alpha-stuff

In your [render](https://sotrh.github.io/learn-wgpu/beginner/tutorial2-swapchain/#render) fn, you can just put `drop(render_pass);` before `encoder.finish()` to avoid the extra `{}` block.

**Comment by sotrh** [comment]
Fixed by  #13
