### ISSUE TITLE
error as the image is drawn before the resize event

### ISSUE THREAD

**Issue by marius851000** [sotrh/learn-wgpu#121]
I have found that, in my evironment, a request_redraw() executed from MainEventsCleared is done before resizing, causing an Outdated error while getting the SwapChainTexture.

The code that produce this error is avalaible here: https://github.com/marius851000/my-learning-wgpu/tree/e3fc300baf1a2b46dccc61cfd6668c935b02a30c , but this also happen with the binary exemple for part 2 for begginer here.

While I don't know how to change the redraw priority, I solved this issue by making the render function faillable, and printing error in log.

Example of what can be found in the log of my version (linking upper)
```
main event cleared
redrawn requested
render
error redrawing: Timeout getting texture

Caused by:
    The underlying surface has changed, and therefore the swap chain must be updated
resize
main event cleared
redrawn requested
render
```

It seem this error doesn't happen when I comment ``window.request_redraw();`` in ``MainEventsCleared``, however.

**Comment by sotrh** [comment]
That's a perfectly acceptable solution as `swap_chain.get_current_frame()` is inherently fallible. `winit` always resizes on startup, so you could avoid the error by skipping a frame until a resize occurs.

Ultimately I should come up with a way to handle this in the tutorial. I may just end up making render fallible as you did.

**Comment by marius851000** [comment]
Thank for the reply. To be more exact it only crash when I resize it manually. It logged three time that the windows was resized before outputting any rendering stuff, but I was otherwise able to practice, just can't resize the window.

**Comment by sotrh** [comment]
The tutorial now properly handles `SwapChainError`s as per #126
