### ISSUE TITLE
Getting a lot of error logs from gfx_backend_vulkan

### ISSUE THREAD

**Issue by MindSwipe** [sotrh/learn-wgpu#135]
I followed the tutorial up to the end of the Pipeline chapter and I'm getting a lot of errors logged out to the console from `gfx_backend_vulkan`, my code is exactly the same as it is in this repo (well, the tutorial3-pipeline directory).

I'm following along on Windows 10 Pro 20H2 (build 19042.746) and installed the Vulkan SDK version 1.2.162.1. Here's an excerpt from the log:

--- 
> [2021-01-24T14:25:37Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-vkMapMemory-size-00680 (-12089429)] : Validation Error: [ VUID-vkMapMemory-size-00680 ] Object 0: handle = 0x5261630000000026, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xff4787ab | VkMapMemory: Attempting to map memory range of size zero The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must be greater than 0 (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkMapMemory-size-00680)
    object info: (type: DEVICE_MEMORY, hndl: 5936134635502174246)
>
> [2021-01-24T14:25:37Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-vkUnmapMemory-memory-00689 (918320700)] : Validation Error: [ VUID-vkUnmapMemory-memory-00689 ] Object 0: handle = 0x5261630000000026, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x36bc763c | Unmapping Memory without memory being mapped: VkDeviceMemory 0x5261630000000026[]. The Vulkan spec states: memory must be currently host mapped (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkUnmapMemory-memory-00689)
    object info: (type: DEVICE_MEMORY, hndl: 5936134635502174246)
>
> [2021-01-24T14:25:37Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-vkCmdPipelineBarrier-dstAccessMask-02816 (1774732925)] : Validation Error: [ VUID-vkCmdPipelineBarrier-dstAccessMask-02816 ] Object 0: handle = 0x162f6031f10, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x69c8467d | vkCmdPipelineBarrier(): pImageMemBarriers[0].dstAccessMask (0x5000) is not supported by dstStageMask (0x1). The Vulkan spec states: The dstAccessMask member of each element of pMemoryBarriers must only include access flags that are supported by one or more of the pipeline stages in dstStageMask, as specified in the table of supported access types (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dstAccessMask-02816)
    object info: (type: COMMAND_BUFFER, hndl: 1524545822480)
>
> [2021-01-24T14:25:37Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-vkMapMemory-size-00680 (-12089429)] : Validation Error: [ VUID-vkMapMemory-size-00680 ] Object 0: handle = 0x9a90ce000000002b, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xff4787ab | VkMapMemory: Attempting to map memory range of size zero The Vulkan spec states: If size is not equal to VK_WHOLE_SIZE, size must be greater than 0 (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkMapMemory-size-00680)
    object info: (type: DEVICE_MEMORY, hndl: 11137628377882558507)
>
> [2021-01-24T14:25:37Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-vkUnmapMemory-memory-00689 (918320700)] : Validation Error: [ VUID-vkUnmapMemory-memory-00689 ] Object 0: handle = 0x9a90ce000000002b, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x36bc763c | Unmapping Memory without memory being mapped: VkDeviceMemory 0x9a90ce000000002b[]. The Vulkan spec states: memory must be currently host mapped (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkUnmapMemory-memory-00689)
    object info: (type: DEVICE_MEMORY, hndl: 11137628377882558507)
>
> [2021-01-24T14:25:37Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-VkDescriptorImageInfo-imageLayout-00344 (-564812795)] : Validation Error: [ VUID-VkDescriptorImageInfo-imageLayout-00344 ] Object 0: handle = 0x162f6031f10, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xde55a405 | vkCmdDraw(): Cannot use VkImage 0x8483000000000025[] (layer=0 mip=0) with specific layout VK_IMAGE_LAYOUT_GENERAL that doesn't match the previous known layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. The Vulkan spec states: imageLayout must match the actual VkImageLayout of each subresource accessible from imageView at the time this descriptor is accessed as defined by the image layout matching rules (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkDescriptorImageInfo-imageLayout-00344)
    object info: (type: COMMAND_BUFFER, hndl: 1524545822480)
>
> [2021-01-24T14:25:37Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-vkCmdDraw-None-02699 (369680064)] : Validation Error: [ VUID-vkCmdDraw-None-02699 ] Object 0: handle = 0xab46ad0000000028, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x1608dec0 | VkDescriptorSet 0xab46ad0000000028[] encountered the following validation error at vkCmdDraw() time: Image layout specified at vkUpdateDescriptorSet* or vkCmdPushDescriptorSet* time doesn't match actual image layout at time descriptor is used. See previous error callback for specific details. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used 
by the VkPipeline bound to the pipeline bind point used by this command (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkCmdDraw-None-02699)
    object info: (type: DESCRIPTOR_SET, hndl: 12341742044367028264)
>
> [2021-01-24T14:25:37Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-vkFreeDescriptorSets-pDescriptorSets-00309 (-1077014252)] : Validation Error: [ VUID-vkFreeDescriptorSets-pDescriptorSets-00309 ] Object 0: handle = 0xab46ad0000000028, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xbfce1114 | vkUpdateDescriptorSets() failed write update validation for VkDescriptorSet 0xab46ad0000000028[] with error: Cannot call vkUpdateDescriptorSets() to perform write update on VkDescriptorSet 0xab46ad0000000028[] allocated with VkDescriptorSetLayout 0x3047930000000016[] that is in use by a command buffer. The Vulkan spec states: All submitted commands that refer to any element of pDescriptorSets must have completed execution (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkFreeDescriptorSets-pDescriptorSets-00309)
    object info: (type: DESCRIPTOR_SET, hndl: 12341742044367028264)
---

**Comment by sotrh** [comment]
Do tutorial 1 and 2 work for you? Of you recently installed Vulkan you might need to restart your computer.

**Comment by sotrh** [comment]
Have you resolved the issue @MindSwipe ? If you haven't do you mind sending me a zipped up trace of your program? You can save a trace using the `trace` parameter to the `request_device` function on `Adapter` https://docs.rs/wgpu/0.6.2/wgpu/struct.Adapter.html#method.request_device The path should be a valid path to a folder.

**Comment by sotrh** [comment]
Since I've updated the tutorial to 0.7, I'm going to close this issue for now. If you still run into this issue feel free to reopen it.
