### ISSUE TITLE
Migrate to 0.7

### ISSUE THREAD

**Issue by sotrh** [sotrh/learn-wgpu#137]
Wgpu has updated to version 0.7. The tutorial should be updated to this latest version.

**Comment by niklaskorz** [comment]
wgpu-rs 0.7 now comes with a method for getting the preferred swapchain format `adapter.get_swap_chain_preferred_format(&surface)` (https://github.com/gfx-rs/wgpu/pull/1142), so the hardcoded `Bgra8UnormSrgb` can finally be replaced :)

**Comment by LoganDark** [comment]
As far as I know, the only changes are a restructuring of the RenderPipelineDescriptor, some renaming, and some `label` fields being added to things that didn't have them before.

**Comment by smsxgli** [comment]
I am following this wonderful tutorial with wgpu 0.7, and I found that in The **Swapchain** **State::new()** section, `wgpu::DeviceDescriptor`'s members has been changed, "label" field added and "shader_validation" field removed.

**Comment by LoganDark** [comment]
> I am following this wonderful tutorial with wgpu 0.7, and I found that in The **Swapchain** **State::new()** section, `wgpu::DeviceDescriptor`'s members has been changed, `label` field added and `shader_validation` field removed.

Just wait till you get to render pipeline, lol

**Comment by Matouche** [comment]
Hi, I've learned wgpu with the first version of this tutorial and it's very nice to see that you're still adding and updating content! As far as I understand it, one of the big changes in 0.7 is that it adds **beta** WGSL support for shaders. Some of their examples have already been migrated to WGSL (e.g. [https://github.com/gfx-rs/wgpu-rs/blob/master/examples/cube/shader.wgsl](https://github.com/gfx-rs/wgpu-rs/blob/master/examples/cube/shader.wgsl)).

AFAIK, it allows an easier build process, getting rid of the shaderc dependency. Do you think it's too soon to consider the migration for this tutorial? Correct me if I'm wrong, but it seems that WGSL is intended to become *the* way to do shaders in WebGPU, so I suppose that sooner or later, the migration will be needed.

**Comment by sotrh** [comment]
Whether we end up using WGSL depends on what sort of shader features it supports. The shadow and the boid examples are WGSL, so we should have everything. I would like to ditch shaderc, but I do worry that WGSL's API isn't stable yet.

**Comment by LoganDark** [comment]
Personally, I prefer GLSL over WGSL. WGSL is just... exceedingly verbose, full of magic sigils and incantations and it looks like compiled machine output that isn't meant to make sense to a real person. The fact that you're expected to write this nonsense is honestly offensive. I'm sticking to GLSL->SPV

**Comment by FrankenApps** [comment]
As far as I understand `naga` will also be able to compile GLSL to SPIR-V.
So `shaderc` could be dropped in either case.

**Comment by sotrh** [comment]
I was looking into switching to `naga`, at the time the GLSL frontend wasn't able to process the shader code for tutorial13. The issue I posted got fixed, so it might be working now. I do plan on switching to WGSL as that will be WebGPU's language of choice moving forward.

That being said I'll probably create a separate issue for integrating `naga` as 0.7 is enough work as is.

**Comment by sotrh** [comment]
Things that still need to be migrated
[ ] Windowless showcase
[ ] Pong showcase
[ ] Framework showcase
[ ] Compute showcase
[ ] Gifs showcase
[ ] The imgui demo

**Comment by ryanpeach** [comment]
Sorry to bump this thread, but I'm confused. Does this tutorial teach "wgpu" or "wgpu-rs" or are they the same thing?

**Comment by niklaskorz** [comment]
@ryanpeach wgpu is the core implementation, that can be used to create bindings on top to different language. wgpu-rs is the idiomatic Rust binding of wgpu, which should be used if you want to write wgpu applications directly in Rust.

**Comment by yutannihilation** [comment]
One thing a bit confusing is that the crate name of wgpu-rs is `wgpu`. So, the word "wgpu" in the tutorial might refer either to wgpu(-core) itself or to wgpu-rs, but I think you don't need to worry about the terminology to walk through the tutorial.
