### ISSUE TITLE
Camera from the docs can't look down enough

### ISSUE THREAD

**Issue by mendes5** [sotrh/learn-wgpu#142]
After playing with the camera a bit, I noticed it can only look down for a bit, and then it slowly stops going down.

I suggest the following at: `code/intermediate/tutorial12-camera/src/camera.rs` in `Camera::calc_matrix`
```rs
    pub fn calc_matrix(&self) -> Matrix4<f32> {
        let (sin_pitch, cos_pitch) = self.pitch.0.sin_cos();
        let (sin_yaw, cos_yaw) = self.yaw.0.sin_cos();

        Matrix4::look_at_dir(
            self.position,
            Vector3::new(
                cos_pitch * cos_yaw,
                sin_pitch,
                cos_pitch * sin_yaw
            ).normalize(),
            Vector3::unit_y(),
        )
    }
```

As we now can look further down, we will need to adjust the code in `CameraController::update_camera` 

```rs
        // Keep the camera's angle from going too high/low.
        if camera.pitch < -Rad(SAFE_FRAC_PI_2) {
            camera.pitch = -Rad(SAFE_FRAC_PI_2);
        } else if camera.pitch > Rad(SAFE_FRAC_PI_2) {
            camera.pitch = Rad(SAFE_FRAC_PI_2);
        }
```

I defined `const SAFE_FRAC_PI_2: f32 = FRAC_PI_2 - 0.0001;` in the same file, but im not sure where `0.0001` should come from... all of this just works™ ([the folks at Three.js did something similar on their lookAt code](https://github.com/mrdoob/three.js/blob/dev/src/math/Matrix4.js#L316))

Any toughts on this? I can submit a MR with those changes and with the documentation updates if it is good enough.

**Comment by sotrh** [comment]
Ya that looks good. Feel free to make that PR. Just remember to modify the `camera.rs` in the threading tutorial as well!
