### ISSUE TITLE
Update cgmath to 0.18

### ISSUE THREAD

**Issue by yutannihilation** [sotrh/learn-wgpu#148]
This isn't very important, but I found `look_at()` used is now deprecated on the v0.18, which was released at Jan 3rd, 2021. So, I think it's good to follow the update to avoid confusion. I might be able to create a pull request for this, but let me just file here for now.

https://docs.rs/cgmath/0.18.0/cgmath/struct.Matrix4.html#method.look_at

**Comment by sotrh** [comment]
Feel free to create a PR for this.
