### ISSUE TITLE
WGSL shaders

### ISSUE THREAD

**Issue by F0Xde** [sotrh/learn-wgpu#156]
Now that almost all wgpu examples [have been ported to WGSL](https://www.reddit.com/r/rust_gamedev/comments/mgvd8d/last_big_wgpurs_example_shaders_are_fully_ported/), would you consider writing the tutorial shaders in WGSL too?

I am aware of the existing discussion in #137, just wanted to bring this up again in the light of said reddit post.

**Comment by yutannihilation** [comment]
As the comments on the Reddit you pointed suggests, I feel the details of WGSL spec is still moving (I too faced the trailing commas issue and needed some time to figure out what was wrong in my code...). This is another example of ongoing breaking changes:

https://github.com/gpuweb/gpuweb/pull/1574

So, it might be a bit (months, not a year probably?) too early? I personally started to learn WGSL by trying porting the GLSL in this tutorial to WGSL, though (c.f. https://github.com/yutannihilation/learn-wgpu-0.7).

**Comment by F0Xde** [comment]
Agreed, currently the spec is still very incomplete and except for the examples there is basically no other documentation / learning material, so maybe it's not time quite yet.
On the other hand seeing the severe lack of documentation it would then also be great to have this tutorial covering WGSL and being the introduction people need.

**Comment by yutannihilation** [comment]
(I think you already saw the conversations there, so this is just for record)
I confirmed it would make sense to have some WGSL tutorials here as there won't be any official one provided anytime soon.

https://matrix.to/#/!XFRnMvAfptAHthwBCx:matrix.org/$WaiZpQREW0ykbbwq7SMRCy-uXgPN9eU4D3_jAX-AkAk?via=matrix.org&via=mozilla.org&via=kyju.org

**Comment by sotrh** [comment]
I've been considering porting the tutorials to WGSL already. I'm a little hesitant as I'm not sure how stable the API is at the moment, nor do I know if the feature set would cover the needs of the current tutorials. I'm going to familiarize myself with WGSL a bit more before making any decisions on this issue.

**Comment by F0Xde** [comment]
After using it for myself I would recommend possibly waiting a bit more, as the API is indeed still changing quite a bit (see `const` to `let`) and in order to have a somewhat recent version of it one would currently need to use the wgpu master branch (which still doesn't have `let` yet).

**Comment by DRKSLV** [comment]
But GLSL still works with wgpu, right?
Sorry i am extremly new to all of this

**Comment by F0Xde** [comment]
Yes, SPIR-V does and will always work with wgpu.

**Comment by sotrh** [comment]
Resolved in #177
