### ISSUE TITLE
Compute Shaders

### ISSUE THREAD

**Issue by ryanpeach** [sotrh/learn-wgpu#159]
The guide shows compute shaders as unsupported.

```rust
        let kind = match extension {
            "vert" => shaderc::ShaderKind::Vertex,
            "frag" => shaderc::ShaderKind::Fragment,
            "comp" => shaderc::ShaderKind::Compute,
            _ => bail!("Unsupported shader: {}", src_path.display()),
        };
```

Does this mean compute shaders are unsupported by wgpu=0.7 or is it just not included in the tutorial?

**Comment by yutannihilation** [comment]
Supported?

> ```rust
>             "comp" => shaderc::ShaderKind::Compute,
> ```

**Comment by sotrh** [comment]
Compute shaders are supported. The last line is a catch all in the case an extension that's not "vert", "frag", or "comp" is passed in. In normal execution it should never be triggered, but rust requires it for match expressions on a none `enum` type.
