### ISSUE TITLE
main() can be async these days so...

### ISSUE THREAD

**Issue by alphastrata** [sotrh/learn-wgpu#162]
Thoughts on updating this one now that `main()` can be async?

`use futures::executor::block_on;`
// Since main can't be async, we're going to need to block
`let mut state = block_on(State::new(&window));`

```
#[async_std::main]
async fn main() {
    say_hello().await;
}
 ```

Forgive me if there's some reason `async` cannot be used as a result of something deep with the library...

**Comment by sotrh** [comment]
I was not aware of `async_std`. I'm definitely open to switching to using it.

**Comment by alphastrata** [comment]
Love your work mate :)
