### ISSUE TITLE
Shaderc binary setup on macOS

### ISSUE THREAD

**Issue by qmathe** [sotrh/learn-wgpu#168]
Here are a few suggestions to make the shaderc library easier to install on macOS. I didn't compile it from source, but downloaded the lib binary from Shaderc Github repository. 

For the first two tutorials, I had to export `SHADERC_LIB_DIR=xxx/shaderc/lib`. 

Starting from tutorial 3, I also add to go through the following steps:
- export `DYLD_FALLBACK_LIBRARY_PATH=xxx/shaderc/lib`
- compile and watch the system complains about: _xxx/shaderc/lib/libshaderc_shared.1.dylib: code signature in (xxx/shaderc/lib/libshaderc_shared.1.dylib) not valid for use in process using Library Validation: library load disallowed by system policy_
- go to _System Preferences > Security > General_ and allows the library to be opened
- recompile and tap _Open_ in the system dialog box asking whether the library should be opened or not

Thanks a lot for this tutorial, it's awesome! I don't want to think at how much time I would have lost without it 😅

**Comment by sotrh** [comment]
I'm considering removing shaderc as a dependency in favor of naga either by replacing all the code with wgsl, or using naga in the build script. I'm going to keep this issue around as Mac users will likely find this info useful, but I'm going to hold off on adding it to the tutorial for now.

**Comment by qmathe** [comment]
ok, I'll keep an eye on the changes you make to test them on macOS.

**Comment by sotrh** [comment]
Since I've removed shaderc as a dependency, I'm going to close this issue.
