### ISSUE TITLE
Each texture and sampler doesn't need its own bind group.

### ISSUE THREAD

**Issue by lwiklendt** [sotrh/learn-wgpu#176]
There is a sentence "For each texture and sampler we create, we need to create its own `BindGroup`." This is not true. Each texture and sampler needs to be added to a bind group but creating a dedicated bind group for each texture and sampler means you will quickly reach the max bind group limit of the device, which is 4 by default.

**Comment by sotrh** [comment]
According to the [wgpu docs](https://docs.rs/wgpu/0.8.1/wgpu/struct.Limits.html#structfield.max_bind_groups) the limit is on how many bind groups can be **attached** to a pipeline, not how many can be **created**. You can create more than 4 bind groups.

**Comment by lwiklendt** [comment]
Still, it is completely untrue that "For each texture and sampler we create, we need to create its own BindGroup."
