### ISSUE TITLE
Error In "Working with Lights" Chapter

### ISSUE THREAD

**Issue by ViniciusCoral** [sotrh/learn-wgpu#189]
In "Seeing the light" there is an error in "light.wgsl" shader that makes the cube rendering wrong.

In the struct Uniform, the view_pos: vec4<f32> field should be removed, or the cube is rendered flat.

struct Uniforms {
    view_proj: mat4x4<f32>;
};

**Comment by sotrh** [comment]
The existing implementation is correct. Even though `light.wgsl` doesn't use `view_pos` it needs to be there because it's defined in the `Uniforms` struct in rust. If I take it out the light disappears entirely as the `Uniforms` struct in `light.wgsl` won't be aligned to the rust version properly.

**Comment by ViniciusCoral** [comment]
Yes. It's correct for the end of the chapter.

But until the "Seeing the light", when we try to execute the code as instructed, there is an error in the rendered the cube, because the change in the Uniforms struct in Rust has not yet been mentioned.

**Comment by sotrh** [comment]
Oh, I see. That's a good catch.
