### ISSUE TITLE
Modifying enabling the Vulkan backend on all platforms causes cargo error 

### ISSUE THREAD

**Issue by eulertour** [sotrh/learn-wgpu#191]
Running `cargo metadata` on the `Cargo.toml` file described at https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#vulkan-portability-layer yields an error:

`cargo.toml`:
```
[dependencies]
image = "0.23"
winit = "0.24"
cgmath = "0.18"
env_logger = "0.8"
log = "0.4"
futures = "0.3"

[dependencies.wgpu]
version = "0.8"
features = ["vulkan-portability"]
```

`cargo metadata` output:
```
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
error: failed to select a version for `wgpu`.
    ... required by package `learn_wgpu v0.1.0 (/home/devneal/github/learn_wgpu)`
versions that meet the requirements `=0.8.1` are: 0.8.1

the package `learn_wgpu` depends on `wgpu`, with features: `vulkan-portability` but `wgpu` does not have these features.


failed to select a version for `wgpu` which could resolve this conflict
```

This is after removing the `wpgu` field from the `[dependencies]` section as described in the section. Updating the version field under `[dependencies.wgpu]` has no effect.

**Comment by sotrh** [comment]
They've removed the `vulkan-portablity` feature. I'll remove that from the tutorial.
