### ISSUE TITLE
collab with https://github.com/rust-tutorials/learn-wgpu ?

### ISSUE THREAD

**Issue by Lokathor** [sotrh/learn-wgpu#2]
Hi, I'm the maintainer of the `rust-tutorials` github org. I had a contributor who was starting on a wgpu tutorial, but they had some personal issues and essentially won't be able to continue the work.

Luckily, I was pointed to your wgpu tutorial here!

I'd love to know how we might work together. I could just have the `rust-tutorials/learn-wgpu` readme link to your repo, or if you want I can make you a maintainer of that repo and you can move your stuff in and merge the two projects, or however you feel is best.

**Comment by sotrh** [comment]
Sorry for the late reply. I'm open to collaboration. I started this project with the hopes that others would get involved.

**Comment by Lokathor** [comment]
Well I don't know `wgpu` myself, but I can add you as a maintainer of that repo and you can PR in stuff as you go. There's not really a current maintainer of that repo so you're not stepping on anyone's toes or anything

**Comment by krooq** [comment]
It took me quite a while to find a tutorial on wgpu and damn is this a good one.
The word needs spreading that's for sure!
Thanks @sotrh !

**Comment by Lokathor** [comment]
@sotrh hi again. I bumped you up to admin on the https://github.com/rust-tutorials/learn-wgpu repo.

Until you have the time and desire to move this stuff over there, i've made that repo's readme just link people to this repo.

**Comment by shika-blyat** [comment]
So if we want to contribute, we do it here for the moment i guess ?

**Comment by Lokathor** [comment]
Their repo, their rules

**Comment by sotrh** [comment]
Sorry for the lack of communication @Lokathor . Things have been a bit chaotic for me lately. 

As you might have guessed I'm going to keep working on learn-wgpu here, so I'm going to close this issue for now. Thanks for linking me on your page though :)
