### ISSUE TITLE
Present mode field purpose

### ISSUE THREAD

**Issue by shika-blyat** [sotrh/learn-wgpu#20]
Hi.
First of all, thanks for your tutorial. It's well written and explains really well :).
I'm opening this issue because of the explanation about present_mode field purpose in  https://github.com/sotrh/learn-wgpu/blob/master/docs/beginner/tutorial2-swapchain/
> There's no documentation on present_mode as of writing, but my guess is that it defines the rate at which you can acquire images from the swap_chain.

You say this, but afaik it's not *exactly* the purpose of the present_mode field, its purpose is to specify how much image the swapchain can hold and swap between at the same time:
https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain#page_Presentation-mode
I don't know how to phrase this, so i won't open a PR, sorry :sweat_smile:

Hope it helps atleast :slightly_smiling_face:

**Comment by sotrh** [comment]
I'll include a change to this in my update to 0.5
