### ISSUE TITLE
tutorial 3 panic when quickly resize

### ISSUE THREAD

**Issue by ARMnunf** [sotrh/learn-wgpu#200]
thread 'main' panicked at 'Index 0 is already occupied'
\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.9.0\src\hub.rs:169:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by sotrh** [comment]
I wasn't able to reproduce the issue. The tutorial has been updated to 0.9 so you might want to try that. That being said it might be an issue specific to your hardware. If upgrading to 0.9 doesn't work, you should probably go over to https://github.com/gfx-rs/wgpu/issues to file an issue.

**Comment by rokonio** [comment]
I have the same issue when the window is resized at minimum, on 2 differents laptops. I'll make a pull request soon with a quick fix

**Comment by rokonio** [comment]
Sory for the exessive amount of mention
