### ISSUE TITLE
tutorial4 vertex_attr_array error

### ISSUE THREAD

**Issue by orlowang** [sotrh/learn-wgpu#201]
`vertex_attr_array ` macor case **cannot return value referencing temporary value** error

**Comment by sotrh** [comment]
The current workaround for that is to have the return lifetime be `'static`, or specify the vertex attributes directly.

**Comment by sotrh** [comment]
Given that this issue isn't specific to my tutorial, and just the nature of returning a references in Rust, I'm going to close this.
