### ISSUE TITLE
How wgpu::Operations exactly work? (and a bug I found trying to understand)

### ISSUE THREAD

**Issue by cdecompilador** [sotrh/learn-wgpu#209]
Hi, I'm learning wgpu and I have some issues understanding some concepts, the concept of a `Encoder` and a `RenderPass` is something I understand from my little knowledge of vulkan, but this:
```rust
encoder.begin_render_pass(
    &wgpu::RenderPassDescriptor {
        label: Some("Render pass"),

        color_attachments: &[
            wgpu::RenderPassColorAttachment {
                view: &frame.view,
                resolve_target: None,
                ops: wgpu::Operations {
                    load: wgpu::LoadOp::Clear(wgpu::Color {
                        r: 0.1,
                        g: 0.2,
                        b: 0.3,
                        a: 1.0
                    }),
                    store: true
                }
            }
        ],
        depth_stencil_attachment: None
    }
);
```
Here the color attachment what exactly means, what the different `LoadOp` variants mean, why the `store: true` (if I turn it to false in vulkan backend the things get weird and in DX the same).

`store: false` (Vulkan):
![Capture2](https://user-images.githubusercontent.com/36774000/127942563-87560f51-5d9d-493e-bba4-cc6a80bf6a06.PNG)
`store: false` (DX12/11):
![Capture1](https://user-images.githubusercontent.com/36774000/127942578-8620abb5-2ff1-4a33-802f-82d5ec47d7f6.PNG)

**Comment by sotrh** [comment]
The `LoadOp` tells wgpu what to do when you request a new frame from the `SwapChain`. `Clear` means you want the swap chain to clear the new frame with the specified color where as `Load` means the swap chain will use what ever data is currently on the swap chain texture. As swap chain textures are recycled from previous frames the data on them may be from a previous frame, or potentially random data. Clearing the frame costs some performance, so if you're going to draw to the entire frame anyways it may be advantageous to use `Load`.

As for the `store` field, from what I can tell it tells the swap chain whether or not to keep the data from the current frame. Different graphics backends (Vulkan, DX, etc.) likely handle this differently and you'd have to ask the wgpu devs for more specifics. As for it's use, the only reason I could see is if you have a pipeline that requires a texture to output to, but you don't care/need the data saved to it.

Hope that helps
