### ISSUE TITLE
Update to wgpu-rs 0.5.

### ISSUE THREAD

**Issue by StarArawn** [sotrh/learn-wgpu#21]
Like the title says.

**Comment by Phaiax** [comment]
CullMode must be `wgpu::CullMode::None` in tutorial 3 with wgpu-rs 0.5

**Comment by telastrus** [comment]
Also, for the swapchain tutorial, `wgpu::Adapter::{request, request_device}` is async now, so you'll likely need futures

**Comment by Phaiax** [comment]
> CullMode must be `wgpu::CullMode::None` in tutorial 3 with wgpu-rs 0.5

Oh my innocent past self :smile: 
Not that I know what CullMode is, I can say that the y axis direction has changed. (That means that my triangle was upside-down but i did not notice that^^. But it looks much cooler that way, anyway.)

Still innocent regards, Daniel

**Comment by sotrh** [comment]
I'm in process of updating. It might take awhile.

**Comment by shika-blyat** [comment]
I'd like to help, but i don't want to do the work twice, could you list tutorials you already updated, tutorials you're still working on and tutorials that i (and other potential contributors) could update ?

**Comment by YRainbbbb** [comment]
I wanted to update it before，but there's a bug in the wgpu document.

**Comment by shika-blyat** [comment]
the bug is now fixed, you can build the doc locally, even if it doesn't work on crates.io doc instance yet

**Comment by YRainbbbb** [comment]
Ok,I see that @sotrh  has started writing a branch called 0.5.
In order not to overlap with his work, I started upgrading the Wgpu from the latter part.

**Comment by sotrh** [comment]
I merged you're changes @YRainbbbb. I'm working on tutorial 6 (the camera/uniforms one) currently

**Comment by sotrh** [comment]
I'm going to make a final pass through the main tutorial code. If any one wants to help with the migration, the `showcase` folder is still needs to be updated.

**Comment by sotrh** [comment]
Be aware that I'm using `wgpu = 0.5.0`. Using the GitHub url might be more up to date, but it provides an inconsistent experience for readers as the version currently on the `wgpu` repo might differ from the code in the tutorials. Given how how often the code has been changed, I feel it's best to lock the tutorial down to the latest stable version.
