### ISSUE TITLE
Possible mistake in Blinn-Phong shading implementation

### ISSUE THREAD

**Issue by azymohliad** [sotrh/learn-wgpu#22]
Hi. I just finished the light tutorial, and Blinn-Phong shading doesn't seem to work right.

So `v_position`, which is later used in the fragment shader to determine the direction to the camera, is calculated in the vertex shader like this:
```
    // Get the position relative to the view for the lighting calc
    v_position = gl_Position.xyz / gl_Position.w;
```
I'm not sure what the division by `.w` component does, but as I understand, `v_position` shouldn't be projected to screen coordinates as `gl_Position` is. I separated view and projection matrices, passed them separately in the uniform, and applied only view matrix to `v_position` likes this:
```
layout(set=0, binding=0) uniform Uniform {
    mat4 u_view;
    mat4 u_proj;
};

void main() {
    // ...
    vec4 view_position = u_view * vec4(a_position, 1.0);
    v_position = view_position.xyz / view_position.w;
    gl_Position = u_proj * view_position;
}
```
And after that it seems to work correctly. Does this make sense?

And btw, thank you very much for great tutorials and my ticket to graphics world with Rust!

**Comment by sotrh** [comment]
I've actually rewritten the lighting tutorial, but you're gix likely would work.
