### ISSUE TITLE
Incorrect Information in The Pipeline

### ISSUE THREAD

**Issue by TheBlueFireFox** [sotrh/learn-wgpu#231]
As I was studying your tutorial, I noticed a small? mistake. 

In the [pipline](https://sotrh.github.io/learn-wgpu/beginner/tutorial3-pipeline/#how-do-we-use-the-shaders) section, when creating the shader you use the (in the current wgpu version [0.10.1](https://docs.rs/wgpu/0.10.1/wgpu/struct.ShaderModuleDescriptor.html)) not supported `flags` attribute. 
I do not know (currently) if the example would still work without the flag, but you do need to know of this.

Thank you for your hard work creating the tutorial.

**Comment by sotrh** [comment]
Good catch. That's probably leftover from the 0.10 migration
