### ISSUE TITLE
memory leak in tutorial3-pipeline

### ISSUE THREAD

**Issue by prideout** [sotrh/learn-wgpu#260]
I tried cloning the repo and doing cargo run --bin tutorial3-pipeline on my M1 MacBook, it looks great but accumulates several gigabytes of memory in less than a minute.
<img width="539" alt="139753690-4bb159e8-79d8-478e-b426-aa0538a739da" src="https://user-images.githubusercontent.com/1288904/139753887-511fcb32-b04e-4a7a-b4ec-018a9a5a720b.png">

**Comment by prideout** [comment]
Note: this does not occur on my windows machine, only my mac.

**Comment by prideout** [comment]
See also https://github.com/gfx-rs/wgpu/pull/2092

**Comment by FrankenApps** [comment]
Seems to be a duplicate of #207 which is also covered in https://github.com/gfx-rs/wgpu/issues/1783 ?

**Comment by prideout** [comment]
Yes, maybe we need to wait until the next version of wgpu gets released.

**Comment by sotrh** [comment]
I'm going to close this as discussion on this issue is already being carried out.
