### ISSUE TITLE
Why is resize method async in the 0.5 branch ?

### ISSUE THREAD

**Issue by shika-blyat** [sotrh/learn-wgpu#27]
As the title says, i'm wondering why the method is labelled as async

**Comment by sotrh** [comment]
When I started doing the rewrite, I was expecting more of the `wgpu` methods to return `Future`s. The only ones I've run into are for the `adapter` code, but I've been busy trying to migrate everything else, so I haven't bothered to remove the `async` keyword.

**Comment by shika-blyat** [comment]
Oh okay. you're going to fix it, or do you want me to open a PR for it ?
