### ISSUE TITLE
Should we use the "latest" version for docs.rs link ?

### ISSUE THREAD

**Issue by Paulo-21** [sotrh/learn-wgpu#278]
**Should we use the "latest" version for docs.rs link ?**

Like : https://docs.rs/wgpu/latest/wgpu/

We will no longer have to update every link

**Comment by sotrh** [comment]
Hmm, my only qualms with doing that would be when wgpu updates and I haven't updated the code, then the references in the docs wouldn't be up to date. That might motivate to migrate things quicker though.

**Comment by yutannihilation** [comment]
As they are getting stabler nowadays, I think it's time to consider using the "latest". Actually, I made a pull request to update these links (https://github.com/sotrh/learn-wgpu/pull/297) but all of them survived in the latest version.
