### ISSUE TITLE
missing `multiview`

### ISSUE THREAD

**Issue by lf94** [sotrh/learn-wgpu#282]
```
error[E0063]: missing field `multiview` in initializer of `RenderPipelineDescriptor<'_>`
  --> src/main.rs:76:56
   |
76 |   let render_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
   |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `multiview`
```

This is missing in "The Pipeline" chapter of the book. :slightly_smiling_face:

**Comment by lf94** [comment]
It seems setting it to None would suffice: https://docs.rs/wgpu/0.12.0/wgpu/struct.RenderPipelineDescriptor.html

**Comment by sotrh** [comment]
Wgpu updated again huh? I'm going to create an issue for 0.12. I'll reference this issue their. Then close this, I probably won't be able to get to it until after Christmas.

**Comment by sotrh** [comment]
Feel free to add any other issues you find to #283
