### ISSUE TITLE
Possible typo: not "false positives" but "false negatives"?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [sotrh/learn-wgpu#286]
In the `tutorial2-surface`, there is a following description:

> You should be using at least version `1.2.182` as older versions can give out some false positives.

Do you actually mean a "false positives?"  I'm not familiar with vulkan at all, nor am I really good at English, but as far as I understand, it outputs assertion errors that do not actually harm, right?  Then this should be "false negatives."

**Comment by sotrh** [comment]
I think false positives is fine here. You can think of it in terms of a medical diagnosis. A false positive cancer diagnosis means that the doctors thought that a person has cancer while they actually don't. The validation layers are positive that their are errors, but they are false: hence false positive. False negatives would mean that the layers didn't find any errors, but their actually are errors.

**Comment by TonalidadeHidrica** [comment]
Oh yes, positive and negative refer to whether it is detected or not, but not to whether it is good or not.  That's totally an issue on my English skill, sorry for the bother.
