### ISSUE TITLE
DeviceEvent does not capture keystrokes on macOS

### ISSUE THREAD

**Issue by yogarasu** [sotrh/learn-wgpu#288]
I'm sorry if it's an existing problem.
As I proceeded through this tutorial 12, I noticed that I wasn't capturing keystrokes.

The environment I'm using is macOS 12.1 on a Macbook Pro 2021 M1 Max.

If not my misunderstanding,
As far as this issue is concerned, it could be a winit issue.
https://github.com/rust-windowing/winit/issues/1470

It might be possible to avoid it by using WindowEvent, but it was a pitfall for Mac users, so I reported this issue for the time being.

**Comment by yogarasu** [comment]
By returning from DeviceEvent to WindowEvent while referring to the changes below, I was able to confirm that the key input was captured by macos.

https://github.com/sotrh/learn-wgpu/commit/12569be5de0ef548d06472b40a66db253caec7fe#diff-79fcb339ca91890e413848ef216ff7b58959054fec2993cc5e93d4c0660ad4a3

**Comment by sotrh** [comment]
Are mouse events working fine?

**Comment by yogarasu** [comment]
@sotrh 
Yes it works.

In the example of Tutorial 12, you can check the operation of DeviceEvent other than DeviceEvent :: Key.
https://github.com/sotrh/learn-wgpu/blob/master/code/intermediate/tutorial12-camera/src/main.rs#L535

**Comment by sotrh** [comment]
Do you mind making a PR for this?

**Comment by sotrh** [comment]
Looks like this is a problem on WASM as well. I'll add a fix for it on the web2 branch
