### ISSUE TITLE
Source code not updated on the website

### ISSUE THREAD

**Issue by Hekno25** [sotrh/learn-wgpu#289]
The source code for the [texture bind group layout](https://sotrh.github.io/learn-wgpu/beginner/tutorial5-textures/#textureviews-and-samplers) section hasn't been updated for wgpu 0.12 but it has been updated in [here](https://github.com/sotrh/learn-wgpu/blob/eaeb7931a1b8fe379ec7a1855bae6fd988237458/code/beginner/tutorial5-textures/src/main.rs) on line 139.

I'm sorry I didn't just make a PR. I'm not sure how to best reword the comments...

**Comment by sotrh** [comment]
Should be fixed as per #289
