### ISSUE TITLE
Improve the descriptions about WebGPU and SPIR-V

### ISSUE THREAD

**Issue by yutannihilation** [sotrh/learn-wgpu#299]
(Disclaimer: I'm not an expert about this, and I didn't follow the discussions on this in the last year, so I might be wrong...)

I feel the description on tutorial 3 is somewhat outdated. For example,

> WebGPU supports two shader languages natively: SPIR-V, and WGSL.

but, while **wgpu** does support it (behind the feature flag `spirv`), IIUC, the WebGPU spec doesn't support SPIR-V.

Actually, Chrome currently does, but the support will be removed according to [the webgpu's wiki](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status):

> Note Chromium currently supports SPIR-V, but support will be removed in favor of WGSL, which is under development.

Also, is this true?

> WGSL's development focuses on getting it to easily convert into SPIR-V.

I thought naga now converts WGSL directly to the format corresponding to the backend, so, except when the backend is Vulkan, wgpu doesn't convert to SPIR-V.

**Comment by yutannihilation** [comment]
I asked on the Matrix: https://matrix.to/#/!FZyQrssSlHEZqrYcOb:matrix.org/$_a3emiOPkywUdE6xYdzMWVNjjBxYFvDNKMHIdhr4CjM?via=matrix.org&via=mozilla.org&via=tchncs.de

**Comment by sotrh** [comment]
Yeah that section should be changed. I'm currently working on getting web examples working for all the tutorials, so if you want to create a pull request that would be great.

You can use the official WGSL spec as a basis. https://www.w3.org/TR/WGSL/#intro

I can come in later and refine the wording to fit my style.

**Comment by yutannihilation** [comment]
Thanks, I'll try to create a pull request!
