### ISSUE TITLE
CameraController ignores Up / Down

### ISSUE THREAD

**Issue by yutannihilation** [sotrh/learn-wgpu#300]
`CameraController` has attributes `is_up_pressed` and `is_down_pressed`, but it seems it's not used in anywhere. Are there any missing code that you planned to add? If it's not used, I think it's fine to remove them.

**Comment by sotrh** [comment]
I never meant to add any up and down movement, but it would probably be a good idea to do so. It would be similar to the left and right movement, but it would be constrained to 90 degrees up and down.

**Comment by yutannihilation** [comment]
Thanks for clarifying. Then, how about removing them for now? While it might be obvious from the code, I needed some minutes to figure out why pressing Space doesn't make any moves. Maybe it's a good idea to remove the unused variable in order not to confuse the beginners like me.

https://github.com/sotrh/learn-wgpu/pull/302
