### ISSUE TITLE
Modifications to the default camera position are not mentioned in guide

### ISSUE THREAD

**Issue by rhysd** [sotrh/learn-wgpu#306]
Hi, I noticed the default camera position is different from my implementation and the screenshot in the guide while I was doing Tutorial 8. After comparing my source with the source in this repo, I understood the default camera position was different.

The default camera positions are modified as follows:

- Tutorial 6: `(0.0, 1.0, 2.0)`
- Tutorial 7: `(0.0, 5.0, 10.0)`
- Tutorial 8: `(0.0, 5.0, -10.0)`

**Comment by sotrh** [comment]
Hmm, I'm not sure why the camera position changes between tutorials 7 and 8. The change between 6 and 7 makes sense. I may change tutorial 7 to use tutorial 8's camera position. The change between tutorial 6 and 7 should definitely be documented though.

**Comment by rhysd** [comment]
The reason tutorial 8 changed Z position from 10 to -10 is that looking at textures from front shows nothing. We only draw back face of textures. (We specified `wgpu::Face::Back` cull mode.)

So changing the Z position between 7 and 8 makes sense to me.

Here are screenshots of tutorial 8:

### `eye: (0.0, 5.0, -10.0)`

<img width="912" alt="" src="https://user-images.githubusercontent.com/823277/149650940-a8107ed2-b49b-4ed4-bd50-72c7ee0d9bbc.png">

### `eye: (0.0, 5.0, 10.0)`

<img width="912" alt="スクリーンショット 2022-01-16 16 16 44" src="https://user-images.githubusercontent.com/823277/149650988-f7b145b5-704b-4abe-9660-199555606fbb.png">

**Comment by sotrh** [comment]
So I figured out what the problem was. At some point the vertex data for tutorial 8 got inverted. Here's what it was in tutorial 8:

```rust
const VERTICES: &[Vertex] = &[
    Vertex {
        position: [-0.0868241, -0.49240386, 0.0],
        tex_coords: [1.0 - 0.4131759, 1.0 - 0.00759614],
    }, // A
    Vertex {
        position: [-0.49513406, -0.06958647, 0.0],
        tex_coords: [1.0 - 0.0048659444, 1.0 - 0.43041354],
    }, // B
    Vertex {
        position: [-0.21918549, 0.44939706, 0.0],
        tex_coords: [1.0 - 0.28081453, 1.0 - 0.949397],
    }, // C
    Vertex {
        position: [0.35966998, 0.3473291, 0.0],
        tex_coords: [1.0 - 0.85967, 1.0 - 0.84732914],
    }, // D
    Vertex {
        position: [0.44147372, -0.2347359, 0.0],
        tex_coords: [1.0 - 0.9414737, 1.0 - 0.2652641],
    }, // E
];
```

Here is the vertices from tutorial 7:

```rust
const VERTICES: &[Vertex] = &[
    Vertex {
        position: [-0.0868241, 0.49240386, 0.0],
        tex_coords: [0.4131759, 0.00759614],
    }, // A
    Vertex {
        position: [-0.49513406, 0.06958647, 0.0],
        tex_coords: [0.0048659444, 0.43041354],
    }, // B
    Vertex {
        position: [-0.21918549, -0.44939706, 0.0],
        tex_coords: [0.28081453, 0.949397],
    }, // C
    Vertex {
        position: [0.35966998, -0.3473291, 0.0],
        tex_coords: [0.85967, 0.84732914],
    }, // D
    Vertex {
        position: [0.44147372, 0.2347359, 0.0],
        tex_coords: [0.9414737, 0.2652641],
    }, // E
];

Switching to use tutorial 7's vertex data, and switching to use `eye: (0.0, 5.0, 10.0).into(),` fixes the issue.
