### ISSUE TITLE
Textures and bind groups

### ISSUE THREAD

**Issue by WSeegers** [sotrh/learn-wgpu#31]
Some minor things I found that may be incorrect.

In Textures and bind groups.

`let diffuse_rgba = diffuse_image.as_rgba8().unwrap();`

If I'm not mistakes `diffuse_rgba` -> `rgba`?

```
let buffer = device.create_buffer_with_data(
    &rgba, 
    wgpu::BufferUsage::COPY_SRC,
);
```

It seems like the size variable in the same section is a mistake.
```
let size = wgpu::Extent3d {
    width: dimensions.0,
    height: dimensions.1,
    depth: 1,
};
```
This would redefine `let size = window.inner_size();`.

By the way thank you for the amazing work.
Will pop in a PR for this when I've run through the tut.

**Comment by sotrh** [comment]
Good catch :)

**Comment by sotrh** [comment]
Looks like the issue has been fix. Thanks for finding it though :)
