### ISSUE TITLE
Ambiguous expectation for normal map handedness

### ISSUE THREAD

**Issue by roudy16** [sotrh/learn-wgpu#313]
The `cobblestone-normal` and `cube-normal` bitmaps use a different handedness, specifically the meaning of the 'G' channel is flipped between the two. Depending on which one should be "correct" in the tutorial the model bitangent calculation should be adjusted.

Notice the `cobblestone-normal` has more green when normals point down (-Y) and the `cube-normal` has more green when normals point up (+Y).

**Comment by sotrh** [comment]
Interesting, which one would be correct assuming I made no changes?

**Comment by roudy16** [comment]
@sotrh Sorry for delay, I've opened #327. I think that is the least invasive way to use the normal map coordinate system you want, another approach would be to update all the shaders to flip the Y value.

**Comment by sotrh** [comment]
Should be fixed by #327
