### ISSUE TITLE
Stop rendering when window is minimized and resume on unminimize

### ISSUE THREAD

**Issue by HeavyRain266** [sotrh/learn-wgpu#328]
Hello, instead of workaround in `State::resize()`, tutorial should teach us how to drop rendering when window area is equal to 0 and resume when it's greater than 0. For now whem window is minimized, swapchain spam "Outdated" in console which doesn't feel right at all.

Wanted to implement it myself as PR but I don't really understand how to drop/resume rendering yet.

**Comment by sotrh** [comment]
Stopping rendering is as simple as not calling the `render()` function. That's definitely something I should look into, as burning cycles while minimized is not ideal.

**Comment by HeavyRain266** [comment]
After doing some research, there are 2 simple solutions.
1. Drop `state.render()` on `SurfaceError::Outdated` as in
```rs
Err(wgpu::SurfaceError::Outdated) => drop(core.render())
```
2. From what someone on discord said, you can simply reconfigure surface on `SurfaceError::Outdated` because wgpu auto clear all resources.
