### ISSUE TITLE
Sentence ends abruptly in tutorial2-surface

### ISSUE THREAD

**Issue by MichaelMcDonnell** [sotrh/learn-wgpu#330]
The following sentence in tutorial2-surface ends abruptly:

> There are cases when you wouldn't want to but those

I don't know enough about wgpu yet to tell what those cases are.

Thank you for this excellent documentation btw! It is a joy to read :-)

**Comment by sotrh** [comment]
My guess is it's supposed to say "those are out of scope for this tutorial.", but I don't remember.
