### ISSUE TITLE
"Textures and bind groups" "Cleaning things up" mentions `CommandBuffer` without using it

### ISSUE THREAD

**Issue by kpreid** [sotrh/learn-wgpu#333]
In https://sotrh.github.io/learn-wgpu/beginner/tutorial5-textures/#cleaning-things-up :

> Note that we're returning a `CommandBuffer` with our texture. This means we can load multiple textures at the same time, and then submit all their command buffers at once.

But the code does not mention `CommandBuffer` at all. I think this might be left over from an older wgpu API?

**Comment by sotrh** [comment]
That's correct, in previous versions of wgpu you needed to load textures by using a command encoder, while you can still do that it's easier to use the `write_texture` method on the queue.
