### ISSUE TITLE
Buffer Memory Layout Info

### ISSUE THREAD

**Issue by teoxoy** [sotrh/learn-wgpu#343]
Hi, I've seen the disclaimer below on the hosted version of the website and I thought it might be useful to share a [resource](https://gist.github.com/teoxoy/936891c16c2a3d1c3c5e7204ac6cd76c) where I've managed to gather information about memory layouts and also let you know about the [`encase`](https://github.com/teoxoy/encase) project I've been working on (related to the topic of laying out data types into buffers).

https://github.com/sotrh/learn-wgpu/blob/75bc7c4ef7317f467601fc1cb929021ee256674e/docs/showcase/alignment/README.md?plain=1#L5-L6

Thanks for this learning material! I got into wgpu by following your tutorials.

**Comment by sotrh** [comment]
That's a nice write up.  The crate looks interesting too.
