### ISSUE TITLE
challange 3 - Cant seem to draw a triangle on Windows 11

### ISSUE THREAD

**Issue by oguzBatur** [sotrh/learn-wgpu#356]
Hello, I have been trying to learn wgpu by following the examples and I have encountered a problem and I was not able to determine the issue. I'm on Windows 11 and using a NVIDIA graphics card (RTX 2060). I'm able to draw colors, but I'm unable to draw the triangle and I have done everything thats been done in the examples. I have used different backends like DX11 DX12 Vulkan GL and that didnt change anything. I have also tried to change the match arms order, as I thought it may be the cause. But still I was not able to understand it. What can be the issue ?

> As you can see, I have created a windows that has colors inside.
![issue_with_wgpu](https://user-images.githubusercontent.com/88832888/167247131-b3b045ac-9081-489b-b184-7b39d052d260.png)
 
> I have done everything in the examples and as you can see, I have attached my render_pipeline to my render_pass
![render_pass_wgpu](https://user-images.githubusercontent.com/88832888/167247225-428a3dd4-ef84-4566-af22-70c4e8ce5720.png)

as you may have guessed, I'm not very experienced in graphics programming, and If the question seems very basic, I'm sorry.

**Comment by yutannihilation** [comment]
Did you try cloning this repo and running `cargo run --bin tutorial3-challenge`? (It seems we also need to `cargo update -p https://github.com/gfx-rs/wgpu#0.12.0` before `cargo run`. c.f. #357). If it works, there might be some difference between this repo and your code.

**Comment by oguzBatur** [comment]
I have run the challenge code and it seems to draw the triangle, but when I copied the code into my file, it still doesnt work, I checked my shader file, and it seems to be the same with the challenge, I have also checked my dependencies and they seem to be the same, I was curious with the .vert and .frag files in the source code, so I copied them into my own src folder, and it seems to work somehow. Do I had to manually write those files or is it automatically generated ?

**Comment by yutannihilation** [comment]
Oh, glad it works.

> the .vert and .frag files

It's a bit confusing, but these are the GLSL files (and the compiled version, `.spv` files), which I believe are not used now because the WebGPU spec migrated to WGSL.

**Comment by oguzBatur** [comment]
> Oh, glad it works.
> 
> > the .vert and .frag files
> 
> It's a bit confusing, but these are the GLSL files (and the compiled version, `.spv` files), which I believe are not used now because the WebGPU spec migrated to WGSL.

Oh thank you for the clarification. I was really confused by them :D I was able to figure it out by the way, thank you very much for telling me something that I should have thought before posting  :D, and sorry for taking your time

**Comment by HeavyRain266** [comment]
> It's a bit confusing, but these are the GLSL files (and the compiled version, `.spv` files), which I believe are not used now because the WebGPU spec migrated to WGSL.

Wgpu still support SPIR-V

**Comment by yutannihilation** [comment]
@HeavyRain266 
Yes, but I meant SPIR-V files included in this repo are not used (You can see `wgpu::ShaderSource::Wgsl()` is used all around) except for some.

**Comment by yutannihilation** [comment]
@oguzBatur 
No worries! Note that, since `wgpu` and the WebGPU spec itself has been changing rapidly, some the description on tutorial might not be up-to-date. If something won't work while you follow the instructions perfectly, you can check the actual code in this repo.
