### ISSUE TITLE
Resize panic crashes in later tutorials

### ISSUE THREAD

**Issue by ZeroPointTwo** [sotrh/learn-wgpu#36]
Hi and thanks for the great tutorials! I noticed that the tutorials for 9, 10, and 11 all crash when resizing the window. It looks like the issue is that in the `resize` function the depth texture is being created with the old size value because it's happening before the `sc_desc` variable is updated with the new sizes. I was able to fix it by moving the depth texture creation to after the new height and width are set.

Specifically, [this](https://github.com/sotrh/learn-wgpu/blob/0f85fe99a0b1164e17fc2658b9cb64bb768550ef/code/intermediate/tutorial11-normals/src/main.rs#L563) is where I made the change. Thanks again for making these available.

**Comment by sotrh** [comment]
Good catch. I've updated the code.
