### ISSUE TITLE
Compile Errors on Intermediate Tutorials: Branch "Gecko"

### ISSUE THREAD

**Issue by JasonRTBond** [sotrh/learn-wgpu#362]
Total newb here, and just trying to compile and run the tutorials. The intermediate examples seem to have a specific branch of wgpu as a dependency, and I get compile errors related to it. If I replace the dependencies with simply `wgpu = "0.12"` I'm then able to compile and run.

```
 Updating git repository `https://github.com/gfx-rs/wgpu`
error: failed to get `wgpu` as a dependency of package `tutorial10-lighting v0.1.0 (/Users/jasonbond/My Projects/rust_tutorials/learn-wgpu-master/code/intermediate/tutorial10-lighting)`

Caused by:
  failed to load source for dependency `wgpu`

Caused by:
  Unable to update https://github.com/gfx-rs/wgpu?branch=gecko#f99d8604

Caused by:
  object not found - no match for id (f99d8604039549272abf523abc0a2cc2d4ac4fb9); class=Odb (9); code=NotFound (-3)
```

**Comment by yutannihilation** [comment]
The `gecko` branch still exists, but it seems the commit in `Cargo.lock` is gone. Updating it with `cargo update -p https://github.com/gfx-rs/wgpu#0.12.0` also works. I have no idea which is better, though...

c.f. https://github.com/sotrh/learn-wgpu/pull/357

**Comment by sotrh** [comment]
Yeah targeting the gecko branch was a fix for the lighting tutorials on WASM as the 0.12 code has a bug in it that causes shader compilation to panic (https://github.com/gfx-rs/naga/issues/1739). It was working on gecko awhile ago, but that branch is a moving target. I think I'll just switch back to using 0.12 directly with a disclaimer about the WASM code not working.
