### ISSUE TITLE
[question] Why is quat_mul implemented in challenge 7?

### ISSUE THREAD

**Issue by Narcha** [sotrh/learn-wgpu#367]
Why is quat_mul implemented [here](https://github.com/sotrh/learn-wgpu/blob/bcb4282f1ef9e70fa88a518905c532625c38b255/code/beginner/tutorial7-instancing/src/challenge.rs#L289-L315)?
The `cgmath` crate implements quaternion multiplication [here](https://docs.rs/cgmath/0.18.0/src/cgmath/quaternion.rs.html#340-349),
and both implementations look functionally identical to me.

**Comment by sotrh** [comment]
I'm not sure honestly. My guess is that I was unaware that `cgmath` had a quaternion multiplication implemented.

**Comment by Narcha** [comment]
Alright, thanks. Closing this issue as the question is answered, not sure if this is worth "fixing".
I can open a PR if you want, though.

**Comment by sotrh** [comment]
> Alright, thanks. Closing this issue as the question is answered, not sure if this is worth "fixing". I can open a PR if you want, though.

You're welcome to submit a PR
