### ISSUE TITLE
The Challenge in Chapter 8 is confusing

### ISSUE THREAD

**Issue by lucypero** [sotrh/learn-wgpu#378]
The Challenge text:

```
Since the depth buffer is a texture, we can sample it in the shader. Because it's a depth texture, we'll have to use the samplerShadow uniform type and the sampler2DShadow function instead of sampler, and sampler2D respectively. Create a bind group for the depth texture (or reuse an existing one), and render it to the screen.
```

It mentions things like `samplerShadow` as if it's a thing in WebGPU. I believe this is from GLSL. I don't know why this is here as this is not an OpenGL tutorial. There is no "samplerShadow" uniform type. Same with "sampler2DShadow".

[Link to the page](https://sotrh.github.io/learn-wgpu/beginner/tutorial8-depth/#challenge)

**Comment by sotrh** [comment]
Good catch. The names would be `sampler_comparison` and `textureSampleCompare` for the uniform type and function respectively.
