### ISSUE TITLE
Pong web demo is broken

### ISSUE THREAD

**Issue by louisgjohnson** [sotrh/learn-wgpu#382]
On the page: https://sotrh.github.io/learn-wgpu/showcase/pong/#wasm-support

The pong try me button doesn't work.

The error message I received when clicking: `An error occurred loading "pong": Error: Cannot find module './pong/pong.js'`

**Comment by erwanvivien** [comment]
Hello, I believe that the error is again appearing in https://sotrh.github.io/learn-wgpu/showcase/pong/#wasm-support

I'm having `An error occurred loading "pong": Error: Cannot find module './pong/pong.js'` too

**Comment by erwanvivien** [comment]
This message didn't re-open the issue, in case you didn't see @sotrh I'm pinging you :)
