### ISSUE TITLE
Demo flickering and dark blue background

### ISSUE THREAD

**Issue by beoboo** [sotrh/learn-wgpu#385]
Any idea why the example in [this page](https://sotrh.github.io/learn-wgpu/beginner/tutorial3-pipeline/#using-a-pipeline) is flickering and with a dark blue background?

I'm on a Mac M1, and this is with Chrome Version 103.0.5060.134.

https://user-images.githubusercontent.com/210002/181449852-83fcd1ba-be76-4199-abbf-ec0cdd6852aa.mov

**Comment by beoboo** [comment]
This seems related: https://github.com/gfx-rs/wgpu/issues/2909

**Comment by sotrh** [comment]
Does it happen when you mouse over the canvas?

**Comment by beoboo** [comment]
Nope, even when the mouse is outside the canvas.

**Comment by sotrh** [comment]
Hmm, that's a weird one. Does this happen with other WebGL content on your machine? You could take a look at https://threejs.org and see if any of those have similar issues.

**Comment by beoboo** [comment]
I tried many examples on threejs, but no, none of them give the flickering
effect.

**Comment by sotrh** [comment]
A decent work around would be to render a skybox. The wgpu repo has an example of one: https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples/skybox

**Comment by beoboo** [comment]
Thanks a lot, I'll check it out.

**Comment by sotrh** [comment]
I just updated the tutorial to 0.14. Can you confirm if you're still seeing the issue?

**Comment by beoboo** [comment]
I'm not! It's working on chrome and firefox correctly now. I don't know if it's the code though or browser updates. Thanks!
