### ISSUE TITLE
Whats special about clip_position?

### ISSUE THREAD

**Issue by dvreed77** [sotrh/learn-wgpu#391]
Apologize if this isn't the right place to ask.

For the pipeline challenge, why can't we use clip_position to properly color the fragments? When I try using clip_position its a solid yellow color, but the x and y values should be the same as the position vec2 that is created.
```wgsl
@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    return vec4<f32>(in.clip_position.xy, 0.5, 1.0);
}
```

**Comment by sotrh** [comment]
After doing some reading about [builtin values in wgsl](https://www.w3.org/TR/WGSL/#builtin-values), it turns that the value for `@building(position) clip_position` is in [framebuffer coordinates](https://gpuweb.github.io/gpuweb/#coordinate-systems) which means it's the positions relative to the width and height of the framebuffer.

This means that if your window is 800x600, x and y coordinates of `clip_position` will be in the range 0-800 and 0-600 respectively. This is a bit unintuitive as you wouldn't expect the value to change coordinate spaces, but that's how it is. I'll probably add the note about that in the tutorial.

If you want the position values in the fragment shader, you'll need to add it to `VertexOutput`:

```wgsl
struct VertexOutput {
    @location(0) position: vec2<f32>,
    @builtin(position) clip_position: vec4<f32>,
};
```
