### ISSUE TITLE
Ordering of statements in render method

### ISSUE THREAD

**Issue by bbonenfant** [sotrh/learn-wgpu#40]
I was working through this tutorial when got stuck on the "Textures and bind groups" section. When trying to run the code at the "Results" section I hit this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IncompatibleBindGroup. The current render pipeline has a layout which is incompatible with a currently set bind group. They first differ at entry index 0.', /.../wgpu-core-0.5.5/src/command/render.rs:1150:21
```
After looking through your full examples on github I found the discrepancy was that in my render function I had this ordering of method calls:
```rust
render_pass.set_pipeline(&self.render_pipeline);
render_pass.set_vertex_buffer(0, &self.vertex_buffer, 0, 0);
render_pass.set_index_buffer(&self.index_buffer, 0, 0);
render_pass.draw_indexed(0..self.num_indices, 0, 0..1);
render_pass.set_bind_group(0, &self.diffuse_bind_group, &[]);  // Note that this call was last.
```
and your example code has this ordering:
```rust
render_pass.set_pipeline(&self.render_pipeline);
render_pass.set_bind_group(0, &self.diffuse_bind_group, &[]);  // Note that this is the second call.
render_pass.set_vertex_buffer(0, &self.vertex_buffer, 0, 0);
render_pass.set_index_buffer(&self.index_buffer, 0, 0);
render_pass.draw_indexed(0..self.num_indices, 0, 0..1);
```

Switching the ordering fixed the error and I don't understand why that's the case. I think it would be helpful to others if this was highlighted and/or explained at the end of the "The BindGroup" section.

**Comment by sotrh** [comment]
The crash occurs because your trying to draw without binding your bind group. The draw call uses the `render_pipeline`, which expects there to be a valid bind group, and if there isn't I'll panic.

I'll look into adding a warning about that
