### ISSUE TITLE
`include_wgsl!("shader.wgsl")` doesn't work

### ISSUE THREAD

**Issue by drone-ah** [sotrh/learn-wgpu#423]
Great tutorial and I am enjoying going through it - thank you!

I am a beginner in rust as well as a graphics programming.

Within the pipeline chapter, there is a callout about being able to use `include_wgsl!("shader.wgsl")` - i.e.

```
let shader = device.create_shader_module(include_wgsl!("shader.wgsl"));
```

However, this gives me an error

```
120  |         let shader = device.create_shader_module(include_wgsl!("shader.wgsl"));
     |                                                  ^^^^^^^^^^^^ help: a macro with a similar name exists: `include_str`
```

I tried including the `include_wgsl` crate, but that failed with another error:

```
   Compiling include_wgsl v1.1.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> D:\Users\shri\.cargo\registry\src\github.com-1ecc6299db9ec823\include_wgsl-1.1.1\src\lib.rs:1:12
  |
1 | #![feature(proc_macro_span)]
  |            ^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> D:\Users\shri\.cargo\registry\src\github.com-1ecc6299db9ec823\include_wgsl-1.1.1\src\lib.rs:2:12
  |
2 | #![feature(proc_macro_diagnostic)]
  |            ^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
```

I tried all versions of the crate with no luck.

The alternative (original) version works fine though :)

**Comment by sotrh** [comment]
Try `wgpu::include_wgsl!("shader.wgsl")`. That  macro is part of the the wgpu crate. I must have imported the macro directly and forgot to add that to the tutorial.

The `include_wgsl` crate is a different thing. Seems useful, but it requires experimental rust features, thus you can only use it on nightly releases of rust (possibly on beta as well, but I'm not sure). Using the macro in wgpu should be enough though.

**Comment by drone-ah** [comment]
Hey there,

Thank you :) That was it! It's now working as advertised. I also see that the documentation has been updated - fab!

Thanks again,
