### ISSUE TITLE
copy of 0..262144 would end up overruning the bounds of the Source buffer of 196608

### ISSUE THREAD

**Issue by Genius1512** [sotrh/learn-wgpu#441]
I'm currently following this tutorial, but I'm stuck at Textures and Bind groups. When I run my code I get an error:
`Error in Queue::write_texture: copy of 0..262144 would end up overrunning the bounds of the Source buffer of size 196608`
I found out that 262144 = 256 * 256 * 4, and 196608 is 256 * 256 * 3. So I've changed the line `bytes_per_row: NonZeroU32::new(4 * dimensions.0)` in Texture::from_image()  to `3 * dimensions.0`. However, I still get the same error but with other numbers.

Does anyone have an idea where this issue could come from?

**Comment by SirFluffDev** [comment]
Probably the case. I was pulling my hair out over this issue, only to find that I had neglected to type the 'a' in `diffuse_image.to_rgba8();`

**Comment by Genius1512** [comment]
That's what it was, thank you!

**Comment by andrewmoore-nz** [comment]
OMG... this just saved me. Thank you. Searching all of the code for one little missing `a` in a function call. Was about to give up.
