### ISSUE TITLE
The tutorial windows doesn't work in the website

### ISSUE THREAD

**Issue by redstonerti** [sotrh/learn-wgpu#446]
https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#wasm-pack
A few days ago I clicked the button and everything was fine, I click it now and it says this
![image](https://user-images.githubusercontent.com/48157961/215320934-3eaf29ec-3745-4925-835e-d8c9a2dc6c68.png)
It just randomly broke.
Reloading doesn't help, i'm on windows and chrome.

**Comment by sotrh** [comment]
Hmm, that's weird because the other ones are working. I'll look into it.

**Comment by sotrh** [comment]
It seems to be working now. My guess is that you had/have a cached version while the app was getting uploaded.

**Comment by redstonerti** [comment]
![image](https://user-images.githubusercontent.com/48157961/218313365-3899c93c-fd0d-473c-beed-ba63a48da056.png)
It still doesn't work.
