### ISSUE TITLE
Normal maps are using incorrect format.

### ISSUE THREAD

**Issue by StarArawn** [sotrh/learn-wgpu#46]
You can't use `Rgba8UnormSrgb` for normal maps as you'll get very incorrect results. I would suggest using `Rgba8Unorm` instead.

Also you should unpack the normals in the shader as well like:
```glsl
normal = normal * 2.0 - 1.0;
```

**Comment by sotrh** [comment]
I'm not using `normal = normal * 2.0 - 1.0` specifically because I'm using `Rgba8UnormSrgb`. Doing it this way was suggested by the `wgpu` guys. Apparently, according to them, `Rgba8UnormSrgb` outputs colors in the range [-1.0, 1.0], perfect for normals. I'm not an expert on texture formats, but the results look correct to me.

**Comment by jmitchell89** [comment]
You can see the difference here:
https://en.wikipedia.org/wiki/SRGB#/media/File:Cie_Chart_with_sRGB_gamut_by_spigget.png
You lose a lot of range of color by using SRGB. Not to mention it's outside of the typical use case of most engines/tools.

Another article about it:
https://medium.com/@bgolus/generating-perfect-normal-maps-for-unity-f929e673fc57#b86c

**Comment by StarArawn** [comment]
You can see the difference here:
https://en.wikipedia.org/wiki/SRGB#/media/File:Cie_Chart_with_sRGB_gamut_by_spigget.png
You lose a lot of range of color by using SRGB. Not to mention it's outside of the typical use case of most engines/tools.

Another article about it:
https://medium.com/@bgolus/generating-perfect-normal-maps-for-unity-f929e673fc57#b86c

**Comment by cwfitzgerald** [comment]
`Rgba8Unorm` should still work with a `texture2D` in shaders, though both `Rgba8Unorm` and `Rgba8UnormSrgb` return data as `[0.0, 1.0]` when sampled as a float.

**Comment by sotrh** [comment]
The textures appear washed out when I use `Rgba8Unorm` and ` * 2 - 1` scaling.
![Screenshot from 2020-06-07 13-07-12](https://user-images.githubusercontent.com/7904656/83977769-4f8c3f80-a8c0-11ea-83a8-6df77ffd2db7.png)

Sorry about the lack of communication on my part. I've been hunting down running wgpu on Android.

**Comment by StarArawn** [comment]
I would still use SRGB for the color texture as they are typically made in SRGB color space. When you generate normal maps they are generated in linear color space. It does mean when loading the textures in you have to determine whether it is a normal texture or a color texture. In my engine I use a ron file, but you could just as easily have something like: `load_texture(path: Path, is_srgb: boolean)`
