### ISSUE TITLE
In `tutorial1_window` I get a compiler error  that something is not a future. 

### ISSUE THREAD

**Issue by exo-cortex** [sotrh/learn-wgpu#468]
I tried out this tutorial and got an error. I use rustc 1.70.0-nightly at the moment. 

This is the error. 
```
error[E0433]: failed to resolve: use of undeclared crate or module `lib`
 --> src/main.rs:4:24
  |
4 |     pollster::block_on(lib::run());
  |                        ^^^ use of undeclared crate or module `lib`
```

I fixed it by changing the `pub fn new()` into `pub async fn new()`

I just thought someone might be interested. Maybe something changed in rustc and not the async is needed? I am still a beginner.

**Comment by sotrh** [comment]
> I just thought someone might be interested. Maybe something changed in rustc and not the async is needed? I am still a beginner.

That's probably not the issue. The error says that `lib` is not defined which suggests that you weren't importing the crate correctly. Seems like it's working now so I'll close this issue.
