### ISSUE TITLE
Compiler errors after finishing the new() method for State

### ISSUE THREAD

**Issue by str0yd** [sotrh/learn-wgpu#474]
After finishing the new() method in topic https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/#state-new at the end when we return the State struct here:
```
    async fn new(window: &Window) -> Self {
        // ...

        Self {
            window,
            surface,
            device,
            queue,
            config,
            size,
        }
    }
```
First of all we ninja borrow: `window: &Window` was `window: Window` before. This change won't work (it should be window: Window since state owns window from now on).
Because window is now owned by the variable state we now have to check 
`if window_id == state.window.id()` instead of `if window_id == window.id()`

**Comment by sotrh** [comment]
Should be fixed in https://github.com/sotrh/learn-wgpu/pull/456/files
