### ISSUE TITLE
Safety note for create_surface appears off

### ISSUE THREAD

**Issue by tbfleming** [sotrh/learn-wgpu#475]
[create_surface's doc](https://docs.rs/wgpu/latest/wgpu/struct.Instance.html#method.create_surface) has this,

> ### Safety
> * ...
> * `raw_window_handle` must remain valid until **after** the returned `Surface` is dropped.

However, [/beginner/tutorial2-surface/#state-new](https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/#state-new) has this note, which says the opposite.

```rust
// # Safety
//
// The surface needs to live as long as the window that created it.
// State owns the window so this should be safe.
let surface = unsafe { instance.create_surface(&window) }.unwrap();
```

Since [the fields of a struct are dropped in declaration order](https://doc.rust-lang.org/reference/destructors.html), it'd be nice to have a safety comment in the `State` struct that `surface` must be declared before `window` since some devs might be tempted to reorder the fields.

**Comment by sotrh** [comment]
I don't there's any issues with order in structs AFAIK. I think the unsafety comes with using a surface after a window is destroyed. A situation where I could see this is if you create a surface on one thread and pass it to a different thread.

**Comment by tbfleming** [comment]
Does the Surface drop implementation guarantee it doesn't call a native API which uses or drops a native object which requires the window handle isn't already dropped? On all platforms?
