### ISSUE TITLE
Viewing Old Versions

### ISSUE THREAD

**Issue by billyb2** [sotrh/learn-wgpu#476]
Is there anyway you could deploy old versions of learn-wgpu under different subdirectories? Like /old/0.13 as an example.

**Comment by sotrh** [comment]
Theoretically, but I don't want to maintain older versions of the site. While I keep the old branches, they aren't guaranteed to be completely accurate. I try to update as quickly as possible, so typo's and incorrect information can creep in. I'm aware I could isolate the individual commits after the merge, but the system for creating the HTML would have to interact git (which honestly sounds like a pain), or I'd have to keep copies of the files.

Another reason for not doing this is older versions of `wgpu` are not going to get long term support. If you encounter a bug the likely suggestion will be to "use the latest version". If a v2.0 of wgpu comes out (and potentially when 1.0 comes out), then I could see maintaining multiple versions.

**Comment by billyb2** [comment]
Understandable
