### ISSUE TITLE
OPENGL_TO_WGPU_MATRIX constant for NDC conversion is incorrect

### ISSUE THREAD

**Issue by sophrosyne97** [sotrh/learn-wgpu#478]
Starting from the chapter "Uniform buffers and a 3d camera" we are introduced a constant matrix named OPENGL_TO_WGPU_MATRIX to convert between OpenGL's and WGPU's NDC coordinates, which looks like the following:

#[rustfmt::skip]
pub const OPENGL_TO_WGPU_MATRIX: cgmath::Matrix4<f32> = cgmath::Matrix4::new(
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 0.5, 0.0,
    0.0, 0.0, 0.5, 1.0,
);

This doesn't cause any noticeable issues throughout the tutorial since with a Perspective projection the effects are minor, but when trying to work with an orthogonal matrix on my own I realized not only were my vertices getting clipped as if I had half the NDC space that I should, but I could also observe weird effects on the vertices like different z values of the vertices actually showing depth which didn't make sense for an Orthogonal projection. I realized after doing some searching that the matrix should be like this instead:

#[rustfmt::skip]
pub const OPENGL_TO_WGPU_MATRIX: cgmath::Matrix4<f32> = cgmath::Matrix4::new(
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 0.5, 0.5,
    0.0, 0.0, 0.0, 1.0,
);

This way we scale the NDC range down by half and then move it forward by half with a proper translation and scale, making the range properly move from [-1, 1] to [0, 1]. I've noticed some other crates that probably used this tutorial as a guide (since it's easily the best one available online) have copied over this mistake so I suppose the sooner the fix on this the better.

**Comment by sotrh** [comment]
I originally got the matrix from the [wgpu repo](https://github.com/gfx-rs/wgpu), though I can't find it anymore, but it makes sense to change it.

**Comment by miwarnec** [comment]
@Dampfwalze Your post just saved my sanity, thank you.
