### ISSUE TITLE
Zip file link in "Model Loading" tutorial gives 404

### ISSUE THREAD

**Issue by yusdacra** [sotrh/learn-wgpu#48]
The zip file link points to <https://github.com/sotrh/learn-wgpu/tree/master/code/beginner/tutorial9-model/src/res> which is incorrect, it should point to <https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial9-models/src/res/cube.zip> instead.

**Comment by sotrh** [comment]
Fixed in latest commit
