### ISSUE TITLE
[tutorial9-models] Texture coords are not flipped vertically

### ISSUE THREAD

**Issue by tobi1805** [sotrh/learn-wgpu#504]
https://github.com/sotrh/learn-wgpu/blob/67e78d9c65431737dd2df1a605e931bf650a5bf3/code/beginner/tutorial9-models/src/resources.rs#L127

There should be a `1.0 - m.mesh.texcoords[i * 2 + 1]]` to invert v coordinate just as in [texture-tutorial](https://sotrh.github.io/learn-wgpu/beginner/tutorial5-textures/#the-results).

**Comment by sotrh** [comment]
Are you observing textures being flipped on your end?

**Comment by tmff** [comment]
Yeah I had the same issue but the fix provided works.

**Comment by sotrh** [comment]
Do you have a model that I could use to test this?

**Comment by sotrh** [comment]
NVM, I'm seeing the issue now.
