### ISSUE TITLE
Modification for the textures beginner tutorial.

### ISSUE THREAD

**Issue by ThePuzzledDev** [sotrh/learn-wgpu#524]
I was reading the tutorial, and was just wondering why you modify the entire texture coords instead of calling `img.flipv()`. The code would look something like this: 
```
pub fn from_bytes(
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        bytes: &[u8],
        label: &str,
    ) -> Result<Self, ImageError> {
        let img = image::load_from_memory(bytes)?.flipv();
        Self::from_image(device, queue, &img, Some(label))
    }
```
It seems a lot simpler than modifying the coordinate system.

**Comment by sotrh** [comment]
That would make a copy of the texture when you flipped it. Not a big deal for small textures, but if your using 4k textures the copy is more expensive. Flipping the uv coords pretty cheap.
