### ISSUE TITLE
Incorrect parameter for creation of WGPU Instance

### ISSUE THREAD

**Issue by baad-c0de** [sotrh/learn-wgpu#530]
You pass in `wgpu::Backends::all()` will creating your instance.  However, this creates Vulkan, DirectX12 and OpenGL backends on Windows and causes a crash on shutdown on the lastest WGPU.

I think this should be `wgpu::Backends::PRIMARY`.

This fixed my crash any way.

**Comment by sotrh** [comment]
I'll check it out.

**Comment by sotrh** [comment]
Fixed
