### ISSUE TITLE
some setup is needed for proper dev eniorment of the exmple

### ISSUE THREAD

**Issue by nevakrien** [sotrh/learn-wgpu#540]
so I am on firefox in ubuntu and I had an issue where it cached the old version of the code and wont budge 

I added   <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />

and played with the dev settings and this seems to have solve it

**Comment by sotrh** [comment]
What settings did you change?

**Comment by sotrh** [comment]
Closing this for now due to inactivity.
