### ISSUE TITLE
Surface chapter code contains compilation errors!

### ISSUE THREAD

**Issue by Jatinchhabra21** [sotrh/learn-wgpu#548]
I don't understand it fully but in new method of State implementation we are passing reference to a window but when instantiating a surface we are again passing a reference to window (which itself is a reference to window)? This causes compilation error `cannot return value referencing local variable window`.

![Screenshot from 2024-05-20 00-51-55](https://github.com/sotrh/learn-wgpu/assets/57009264/e03fdaf6-c774-4ab3-8bff-bd7b9c0db216)
```Rust
async fn new(window: &'a Window) {}
```

```Rust
instance.create_surface(&window)
```

![Screenshot from 2024-05-20 00-53-54](https://github.com/sotrh/learn-wgpu/assets/57009264/447382b4-c401-45dc-8118-051be70c8058)

**Comment by AndrewDanial** [comment]
Hello! Not sure if this issue is still relevant to you but I got arround this by simply removing the `&` from window, so the line is simply `instance.create_surface(window);`. I also didn't find the `unsafe` block to be necessary.
