### ISSUE TITLE
Question: difference between DynamicImage::as_rgba8() and DynamicImage::to_rgba()

### ISSUE THREAD

**Issue by yutannihilation** [sotrh/learn-wgpu#55]
(Sorry, this might not be a wgpu-related issue. Please feel free to close this if this is not the topic that should be covered in this guide.)

I was stuck on tutorial 9 for a while to find out the difference between my code and the correct answer. In the end, I found I needed to change `img.as_rgba8().unwrap()` to `img.to_rgba()`, but I still don't get how they are different. I'd really appreciate if the guide has some explanation on this. (If this is not worth explaining, can the all tutorials use `to_rgba()` to avoid confusion?)

Until tutorial 8:
https://github.com/sotrh/learn-wgpu/blob/f163d921072c04a8b5f3842a76cdd292243d6368/code/beginner/tutorial8-depth/src/texture.rs#L55

After tutorial 9:
https://github.com/sotrh/learn-wgpu/blob/f163d921072c04a8b5f3842a76cdd292243d6368/code/beginner/tutorial9-models/src/texture.rs#L73

**Comment by sotrh** [comment]
I'm using `to_rgba()` to handle JPGs. PNGs work fine with `as_rgba8()`, as they have an alpha channel. JPGs don't have an alpha channel, and your code will panic if you try to call `as_rgba8()` on one of them.

**Comment by yutannihilation** [comment]
Ah, thanks, I got it! May I create a PR to add your explanation in the guide?

**Comment by sotrh** [comment]
Totally :)

**Comment by yutannihilation** [comment]
Thanks, here it is! #58
