### ISSUE TITLE
How to draw in a dedicated function

### ISSUE THREAD

**Issue by jjbel** [sotrh/learn-wgpu#562]
Hello, and thanks for the excellent tutorial! I'm at the [Pipeline](https://sotrh.github.io/learn-wgpu/beginner/tutorial3-pipeline/)  Section.
Currently, drawing anything requires calling `render_pass.draw()`, where render_pass is created inside the `render()` function.
I was hoping to abstract away the drawing into a dedicated function.
For example, `state.draw_triangle();` for the simple brown triangle in the Pipeline tutorial.
This is because, I want a user of my library to be able to call this function, and the drawing details are abstracted away into `State`

I would put the creation of `render_pass` in a `begin_render` function, and the `queue.submit` and `output.present` in a `finish_render` function.

(I come from a C++/OpenGL context, where the draw calls affect global state, like `glDrawArrays` isn't called on a particular object)

I thought it made sense to make `render_pass` a member variable of `State`, maybe an `Option<wgpu::RenderPass<'a>>`,
but this doesn't work because creating `render_pass` borrows `encoder` mutably.
I tried making `encoder` and `view` member variables too, but that gives me lifetime errors:

```rust
error: lifetime may not live long enough
   --> src/state.rs:180:9
    |
27  | impl<'a> State<'a> {
    |      -- lifetime `'a` defined here
...
163 |     pub fn render(&mut self) -> Result<(), wgpu::SurfaceError> {
    |                   - let's call the lifetime of this reference `'1`
...
180 |         self.render_pass = Some(self.render_encoder.as_mut().unwrap().begin_render_pass(
    |         ^^^^^^^^^^^^^^^^ assignment requires that `'1` must outlive `'a`
```

You can view and run my full code [at my Github](https://github.com/jjbel/learning-wgpu/blob/b482f40f6b5afef5ea93aaa6fc7390e2b1e811f2/src/state.rs#L163
), specifically from lines `22` and `163`

Another thought i had was accepting a closure as an argument of `render()` which calls `render_pass.draw`

Please would someone enlighten me on whether this separation is possible, and how to approach it.
Many thanks!
Apologies, I'm a beginner at Rust. Apologies if Issues isn't the right place to ask this.

**Comment by sotrh** [comment]
Both command encoders and render passes are not meant to kept around. They are only good for one frame. The `RenderPass` keeps a reference to the textures it's going to draw to. In particular the surface textures are referenced after calling [Surface::get_current_texture](https://docs.rs/wgpu/latest/wgpu/struct.Surface.html#method.get_current_texture).

Keeping around a `RenderPass` isn't as useful as it may seem at first. They aren't that expensive to create, and keeping a global copy of one limits what textures you can draw to. Passing in the render pass means that you can draw to any compatible texture.

The OpenGL way of doing this may seems nice, but "internal global state" is the very reason people are moving away from OpenGL and creating things like Vulkan and WebGPU in the first place. It's a lot easier to see a bug when your passing stuff into a function, than when the functions you call affect random parts of the internal state in ways that you can't possible see. I've been working with WebGL for work, and the system is a nightmare to debug.

To answer your underlying question though, `RenderPass`  has a mutable reference to a `CommandEncoder`. In this case the `CommandEncoder` is also a part of `State`. Rust doesn't allow internal references, so what your doing is impossible.

**Comment by jjbel** [comment]
Thanks @sotrh, I understand the flaws of the OpenGL way now. I'll create the render pass every frame. Thanks again!
