### ISSUE TITLE
Tutorial10 was running fine yesterday, today it does not.

### ISSUE THREAD

**Issue by Jeklah** [sotrh/learn-wgpu#563]
#![cfg_attr(feature = "stdsimd", feature(stdsimd))] 

stdsimd is unknown feature.

I have tried deleting the repo and re-cloning hoping that I may have changed something while in the wrong directory, but it still gave the same error after recloning.
I was looking at this repo most of yesterday and even up until bed, it was working no problem.

What's changed?

**Comment by sotrh** [comment]
Feel free to send a link

**Comment by sotrh** [comment]
I'm not sure if it's the same issue, but I fixed an issue with tobj

**Comment by Jeklah** [comment]
I got it working in the end thanks. We could compare repos though if you'd
like?

**Comment by sotrh** [comment]
Glad you got it working. I don't think we need to compare repos, if someone encounters the issue again they can open up a new issue.
