### ISSUE TITLE
Tutorial2 Not Working on Web

### ISSUE THREAD

**Issue by carsonalh** [sotrh/learn-wgpu#573]
I've been going through the tutorials, and have failed to get the turquoise screen of Tutorial2 working on the web.

I followed the example and was able to get it working when built natively, but could not get it working on the web.  Then, to try and see if I had missed something, I cloned this repo, and tried to see if the code here would work.

To see if it was working natively,

```
cargo run --bin tutorial2-surface
```

this worked just fine.  Then, to get it working on the web,

```
wasm-pack build code/beginner/tutorial2-surface --target web
```

Then, to run the outputted web code, I tried creating this demo html file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tutorial2 | Surfaces</title>
</head>
<body>
    <script type="module">
        import init from './pkg/tutorial2_surface.js'
        init({}).then(() => console.log('WASM loaded!'));
    </script>
</body>
</html>
```

This did not even create a canvas element, but instead, this is what I was met with:

![image](https://github.com/user-attachments/assets/a3fd85ed-5fe9-4239-a2e9-63593c90563e)

This was tested on the latest `master`, or commit `ad3d08b917bd5df972ed1721f6c8543f733531db`.

**Comment by sotrh** [comment]
This code works
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learn WGPU</title>
    <style>
        * {
            padding: 0;
            margin: 0
        }
        canvas {
            background-color: black;
        }
    </style>
</head>

<body id="wasm-example">
  <script type="module">
      import init from "./pkg/tutorial2_surface.js";
      init().then(() => {
          console.log("WASM Loaded");
      });
  </script>
</body>

</html>
```
