### ISSUE TITLE
Summer Cleaning

### ISSUE THREAD

**Issue by sotrh** [sotrh/learn-wgpu#61]
I'm creating this issue to document some of the changes and thoughts I'd like to make to the tutorial. Currently there are some issues that make development rather cumbersome.

## 1. Performance

This is probably the biggest issue. The tutorials take quite some time to load up, and also tend to be stuttery. I need to do some research into what's causing the issues. Looking at the current wgpu examples shows that my winit event loop could be improved.

Stuttering also effects getting screenshots. Currently my computer will freeze for a couple seconds whenever I take a screenshot, or change windows. This makes creating new tutorials, and updating old ones difficult.

## 2. The Camera

Currently the camera can only rotate around the scene, and zoom in and out. This works, but it can make it hard to focus in on a particular part of the scene. I'm debating between a Minecraft creative mode style camera were you can move in the x/z freely, and move up and down with the shift/ctrl keys; and a regular flying free cam.

## 3. Difficulty creating new pipelines

Not sure how best to improve this. The difficulty is bind groups are kind of a pain to manage. I need to do some research into different ways of managing bind groups.

## 4. Slowing down development

The WepGPU spec is currently in flux. I haven't been super motivated to create a bunch of new tutorials, as that just means I have to update them when the API changes. On top of that, I'm running out of wgpu specific things to talk about. There are plenty of tutorials on GLSL, and a variety of graphics techniques, and once you know how to use pipelines, buffers, textures etc. adapting these techniques is not too hard. Because of this I'm going to be slowing down the rate that I make tutorials.

That being said, there are a couple things I'd like to do before I go into maintenance mode.

1. Some sort of compute pipeline tutorial. I haven't touched command pipelines at all. I'm thinking some combination of terrain generation, and post processing. I'm also interested in doing a PBR guide.
2. Text, there are libraries that exist to do this: `wgpu_glyph`, `wgpu_imgui`, others I'm unaware of. I want to implement this myself though as I haven't covered alpha blending yet.

**Comment by krooq** [comment]
I love your tutorials. I think they are the perfect amount of technical background and practical examples.

If I may add a request to your summer cleaning..
I'm struggling a bit on the instancing section, I'd like to have some more information on which approach is the "industry standard" and what really differentiates vertex buffer vs storage buffer vs texture in terms of performance/flexibility.
I'd also like to see these instancing tutorials split up into separate tutorials/sections, at the moment it reads as if you would go through each of them one by one to try them out but I think lots of people also use the tutorial as a reference and it helps for them to be complete examples.

**Comment by guidorice** [comment]
@sotrh by "command pipeline" do you mean `GPUComputePipeline` and `GPURenderPipeline`? Something touching on general gpu compute would be great, in any case.

**Comment by sotrh** [comment]
@guidorice I was referring to the `ComputePipeline`. I'll edit the post.

**Comment by sotrh** [comment]
I'm closing this issue for now. I still need to do a compute example, but I've accomplished the other goals on this list.
