### ISSUE TITLE
Update to wgpu-rs 0.6.

### ISSUE THREAD

**Issue by Cupnfish** [sotrh/learn-wgpu#85]
Feels like a lot of work

**Comment by sotrh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [0.6](https://trello.com/c/I7ZX4Dt9/36-06)

**Comment by NeuroWhAI** [comment]
I'm here because compiling beginner tutorial with 0.6 version was failed.
Anyone who want to learn the wgpu with latest version like me, Just see the 0.6 branch of here.
I think it is done at least beginner page.
Thank you sotrh!

**Comment by sotrh** [comment]
Fixed in #90
