### ISSUE TITLE
Inconsistent `light.vert` output type and `light.frag` input type

### ISSUE THREAD

**Issue by cs-cordero** [sotrh/learn-wgpu#86]
First, thanks so much for your tutorial.  I'm learning so much going through it.

Just want to let you know that there's an error in your light shader programs under the lighting intermediate tutorial.
https://sotrh.github.io/learn-wgpu/intermediate/tutorial10-lighting/#seeing-the-light

```
// light.vert
layout(location=0) out vec4 v_color;


// light.frag
layout(location=0) in vec3 v_color;
```

The vertex shader outputs a `vec4`, but the fragment shader expects an input of `vec3`.  This causes creating the light pipeline to fail.  It took me a while to figure this out until after I enabled logging.

**Comment by sotrh** [comment]
Good catch. I'll lump that into my #85 changes
