### ISSUE TITLE
Getting this error when compiling tutorial1

### ISSUE THREAD

**Issue by digital-nomad17** [sotrh/learn-wgpu#89]
I am getting this error when I run the first tutorial.

```
Andrews-MBP:tutorial1-window andrew$ cargo run
    Updating crates.io index
    Updating crates.io index
error: no matching package named `jpeg` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `image v0.23.7`
    ... which is depended on by `tutorial7-instancing v0.1.0 (/Users/andrewcarre/code/rust/learn-wgpu/code/beginner/tutorial7-instancing)`
```

Any ideas?

**Comment by sotrh** [comment]
I've updated the tutorials to 0.6. Try pulling master and then see if you can run it.

**Comment by sotrh** [comment]
I'm going to close this error for now. Seems like a cache issue with cargo. If you figure out the issue, and it has to do with the tutorial, feel free to reopen this issue.
