### ISSUE TITLE
Rust formatting

### ISSUE THREAD

**Issue by rofrol** [sotrh/learn-wgpu#9]
I see that you have some formatting rules for Rust in examples.

Can you commit them to the repo?

https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

**Comment by sotrh** [comment]
I'm actually not using `rustfmt` at all right now. I'm fairly new to Rust, so I wasn't aware it existed

**Comment by rofrol** [comment]
You can look at my neovim/vim configuration for autosaving https://github.com/rofrol/dotfiles/blob/301e4a414cc523c0c4544baf2c3dfb58ce95cf2f/.config/nvim/init.vim#L45

**Comment by rofrol** [comment]
And thanks for your great work :heart:

**Comment by rofrol** [comment]
You can also format all files with cargo fmt

**Comment by rofrol** [comment]
Fixed (?) by https://github.com/sotrh/learn-wgpu/pull/11
