### ISSUE TITLE
Outdated contents in Markdown website, compared to Github repo/directory

### ISSUE THREAD

**Issue by nyanpasu64** [sotrh/learn-wgpu#92]
In the "The Swapchain" section of the tutorial, the `State::new()` block calls `let size = window.inner_size();` twice. I don't think both calls are needed. Was the call intended to go at the beginning or end of the code block?

https://github.com/sotrh/learn-wgpu/blob/master/docs/beginner/tutorial2-swapchain/README.md#statenew

----

Actually I've noticed multiple differences between the .md code and your repo. `State::new()` writes the `adapter` field into `Self = State`, which doesn't exist. This field was removed in the repo at https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial2-swapchain/src/main.rs .

----

Also the code doesn't compile on wgpu 0.6.

----

https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial6-uniforms/src/main.rs#L466
`    self.queue.write_buffer(&self.uniform_buffer, 0, &bytemuck::cast_slice(&[self.uniforms]));`
I suspect the & in `&bytemuck::cast_slice` is redundant and gets silently discarded.

**Comment by sotrh** [comment]
All your suggests LGTM, but I would like some clarification on the following statement.

> Also the code doesn't compile on wgpu 0.6.

Do you mean the code in the repo, or the code you get when you follow along with the tutorial. Also, have you pulled recently? I merged my 0.6 branch into master recently as per #90.

**Comment by nyanpasu64** [comment]
> Also the code doesn't compile on wgpu 0.6.

Only the code blocks you get when you follow along with the tutorial don't compile. And I stopped following 1:1 sometime around "Buffers and Indices".

The only problem I reported that's also present in the repo is the redundant `&`.

I didn't actually clone the repo locally, but am just copying from Github. Maybe I should clone... (though I'm at the point I don't need the tutorial anymore.)

**Comment by sotrh** [comment]
I'll fix the changes you mentioned, and probably do a run through the tutorial myself.

**Comment by sotrh** [comment]
Also, what OS are you running on @nyanpasu64 ?

**Comment by nyanpasu64** [comment]
Windows 10 x64, but I think the APIs that changed are OS-independent.

Also https://sotrh.github.io/learn-wgpu/beginner/tutorial3-pipeline/#compiling-shaders-and-include-spirv includes anyhow as a dependency, but uses failure in the code. This has been fixed in the repo but not the website.

**Comment by sotrh** [comment]
I've fixed the issues you've listed, so I'm going to close this issue for now. If you find anything more, feel free to open a new issue. Thanks :)
