### ISSUE TITLE
create_buffer_with_data

### ISSUE THREAD

**Issue by khuttun** [sotrh/learn-wgpu#93]
This function doesn't seem to exist in wgpu-rs anymore since https://github.com/gfx-rs/wgpu-rs/commit/2512c30e57197e768dce9fa38e3b545099a0831d

**Comment by sotrh** [comment]
You are correct. What part of the tutorial did you see this in? I made a lot of changes for 0.6 as per #90. It's very possible that I missed a few things. The code in the repo should be up to date however.

**Comment by khuttun** [comment]
It’s here
https://sotrh.github.io/learn-wgpu/beginner/tutorial4-buffer/#the-vertex-buffer

The index buffer part seems to use `create_buffer_init` already.

**Comment by sotrh** [comment]
I must have missed that one when I was going through. I'll get that corrected
