### ISSUE TITLE
GLSL usage

### ISSUE THREAD

**Issue by khuttun** [sotrh/learn-wgpu#97]
Would it make sense to state somewhere in the tutorial when shaders are first introduced that the GLSL used is with the Vulkan extension? Not mentioning it might confuse readers familiar with OpenGL but not with Vulkan, if they for example try to look up more information on some of the topics from khronos.org OpenGL docs.

**Comment by kanerogers** [comment]
That would be helpful for someone like me, who is very new to shaders and graphics programming in general. :)

**Comment by sotrh** [comment]
That sounds ok to me. Feel free to submit a pull request.
